name: Backend-CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v6

      - name: Configuration du fichier .env
        run: |
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" > .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env

      - name: Lancement du Docker compose
        run: docker compose up -d --build

      - name: Pause pour le démarrage des services
        run: sleep 20

      - name: Vérification du statut des conteneurs
        run: |
          docker compose ps
          # Cette ligne fait planter le pipeline si un conteneur est arrêté ou unhealthy
          docker compose ps | grep -E "unhealthy|exited" && exit 1 || echo "Tous les conteneurs sont lancés et sains !"

      - name: Nettoyage
        if: always()
        run: docker compose down -v

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v6

      - name: Configuration du fichier .env
        run: |
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" > .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env

      - name: Déploiement
        run: docker compose up -d --build

      - name: Nettoyage
        if: always()
        run: docker compose down -v